title: COGS 108
email: jfleischer@ucsd.edu
description: >-
  COGS 108, Spring 2026 at UC San Diego
tagline: Data Science in Practice

url: "https://COGS108.github.io"
baseurl: "/LectureNotes"

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme
  - jekyll-feed

search_enabled: true

markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .data/
  - docs
  - dev-docs

aux_links:
  "🙋 Piazza": "https://piazza.com"
  "💯 Gradescope": "https://www.gradescope.com"
  "💪 Practice": "https://practice.dsc40a.com"

aux_links_new_tab: true

data_folder: sp26

color_scheme: dark

callouts_level: quiet
callouts:
  highlight:
    title: Caution
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

back_to_top: true
back_to_top_text: "Back to top"

collections:
  demos:
    output: true
    permalink: /demos/:path
    